---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-test-mongodb-nodeport
  namespace: mongodb-test
spec:
  selector:
    app: mongodb-test-mongodb
  type: NodePort
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
      nodePort: 32017