apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-community-operator
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: mongodb
  source:
    repoURL: https://mongodb.github.io/helm-charts
    chart: community-operator
    targetRevision: 0.13.0
    helm:
      releaseName: community-operator
      parameters:
        - name: operator.watchNamespace
          value: "*"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
